### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by N0ct3** [svroonland/TwinRx#2]
Hello Svroonland, 
Are you planing to release a new version of your library as a nuget package? 
From what I have seen, the latest version available on nuget does not support structure, while the latest version of the code on github does.
Did you identify any issue preventing you from promoting it to a release version?
Regards

**Comment by svroonland** [comment]
Hi @N0ct3, thanks for your message and interest in this package. Sorry for the late reply, I did not get a notification about creation of this issue for some reason. 

I was planning on including some more features before I released a new version, but as you can see that did not happen. So I just published the latest master to nuget, 1.1.0.40. 

It's been a while, so let me know if you run into any issues.
